apiVersion: v1
kind: Service

metadata:
  name: netflix-backend
  namespace: dev

spec:
  selector:
    app: netflix-backend

  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}

  type: ClusterIP